name: Build and Deploy Go Telegram Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Checkout кода
    - name: Checkout code
      uses: actions/checkout@v2

    # Шаг 2: Установка Go
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18' # Укажите версию Go, которую используете

    # Шаг 3: Установка зависимостей
    - name: Install dependencies
      run: |
        go mod tidy

    # Шаг 4: Сборка Go проекта
    - name: Build the Go project
      run: |
        go build -o bot main.go

    # Шаг 5: Подключение к серверу и копирование собранного файла
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}  # Использование секретных переменных
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          # Переход в директорию проекта
          cd /root/tgbot || exit 1

          # Копирование собранного файла bot на сервер
          rm -f bot
          scp ./bot ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/tgbot/

          # Запуск нового бота
          pkill -f bot || true
          ./bot &

          # Вывод последних строк лога
          tail -n 10 bot.log
