name: Deploy and Compile Go Telegram Bot

on:
  push:
    branches: [ main ]  # Триггер на пуш в main

jobs:
  deploy-and-compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Compile and Restart Bot
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        # Переходим в директорию с ботом
        cd /root/tgbot
        
        # Компилируем main.go (предполагается, что Go уже установлен на сервере)
        go build -o tgbot main.go
        kill $(cat /root/tgbot/bot.pid) 2>/dev/null || true
        nohup ./tgbot > bot.log 2>&1 &
        
        # Если нужно перезапустить сервис (пример для systemd)
        # sudo systemctl restart tgbot.service
        EOF
