name: Deploy Bot to VDS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VDS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Starting deployment..."
            cd /root/tgbot || exit 1
            echo "Pulled latest changes..."
            git pull origin main || exit 1
            echo "Compiling project..."
            go build -o bot main.go || exit 1
            echo "Killing old bot processes..."
            pkill -f bot || true
            echo "Starting new bot..."
            nohup ./bot > bot.log 2>&1 &
            sleep 5
            echo "Bot started successfully" >> bot.log
            tail -n 10 bot.log
