name: Build and Deploy Go Telegram Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Checkout кода
    - name: Checkout code
      uses: actions/checkout@v2

    # Шаг 2: Установка Go
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18' # Укажите версию Go, которую используете

    # Шаг 3: Установка зависимостей
    - name: Install dependencies
      run: |
        go mod tidy

    # Шаг 4: Сборка Go проекта
    - name: Build the Go project
      run: |
        go build -o bot main.go

    # Шаг 5: Подключение к VDS серверу и деплой
    - name: Deploy to VDS Server via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}           # Укажите ваш VDS сервер (или используйте секрет)
        username: ${{ secrets.SSH_USER }}   # Укажите имя пользователя для SSH (или секрет)
        key: ${{ secrets.SSH_KEY }} # Укажите приватный ключ SSH (секрет)
        port: 22
        script: |
          # Переход в нужную директорию
          cd /path/to/your/project || exit 1

          # Копирование собранного файла bot на сервер
          rm -f bot
          scp ./bot ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/path/to/your/project/

          # Запуск нового бота
          pkill -f bot || true
          nohup ./bot > bot.log 2>&1 &

          # Вывод последних строк лога
          tail -n 10 bot.log
